projects:
  database:
    extensions:
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: mybinding.ts    
      endpoints:
        dev:
          url: 'http://localhost:4466'
          subscription: 'ws://localhost:4466'
  gateway:
    schemaPath: source/schema.graphql
    extensions:
      endpoints:
        dev:
          url: 'http://localhost:4000'
          # subscription: 'ws://localhost:4000'
